# This is free software, licensed under the Apache License, Version 2.0
#
# Copyright (C) 2024 Maizil <maizilpc7@gmail.com>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for coovachilli.
LUCI_DEPENDS:=+luci +coova-chilli
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for coovachilli.
LUCI_MAINTAINER:=Maizil41 <https://github.com/maizil41>

PKG_VERSION:=1.2
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_ARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
